# .github/workflows/deploy.yml
name: Deploy to Contabo

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH to Contabo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22             
          script: |
            echo "Ensure project directory exists"
            mkdir -p /home/${{ secrets.SSH_USER }}/5-oy_imtihon
            cd /home/${{ secrets.SSH_USER }}/5-oy_imtihon

             if [ ! -d .git ]; then
                echo "Cloning repository over HTTPS"
                git clone https://github.com/Bobur815/5-oy_imtihon.git .
            else
                echo "Fetching and resetting to origin/master"
                git fetch origin
                git reset --hard origin/master
            fi


            echo "Stopping containers"
            sudo docker compose down --remove-orphans

            echo "Building and starting containers"
            sudo docker compose up -d --build
