# .github/workflows/deploy.yml
name: Deploy to Contabo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH to Contabo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22             
          script: |
            echo "Ensure project directory exists"
            mkdir -p /home/${{ secrets.SSH_USER }}/5-oy_imtihon
            cd /home/${{ secrets.SSH_USER }}/5-oy_imtihon

            if [ ! -d .git ]; then
              echo "Cloning repository"
              git clone git@github.com:Bobur815/5-oy_imtihon.git .
            else
              echo "Pulling latest changes"
              git fetch origin
              git reset --hard origin/main
            fi

            echo "Stopping containers"
            docker compose down --remove-orphans

            echo "Building and starting containers"
            docker compose up -d --build
